# Generated by Django 5.2.4 on 2025-08-13 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authorization", "0002_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="level",
            field=models.IntegerField(
                default=1,
                max_length=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
