# Generated by Django 5.2.4 on 2025-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecpay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="MerchantID",
            field=models.CharField(default="3002607", max_length=32),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Bank Transfer", "Bank Transfer")],
                default="Credit",
                max_length=32,
            ),
        ),
    ]
