# Generated by Django 5.2.4 on 2025-08-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecpay", "0002_order_merchantid_alter_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="MerchantID",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
