# Generated by Django 5.2.4 on 2025-08-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecpay", "0003_remove_order_merchantid_remove_order_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="merchant_trade_no",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
