# Generated by Django 5.2.4 on 2025-08-12 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfamiliarity",
            name="uq_user_quiz_topic",
        ),
        migrations.RemoveConstraint(
            model_name="userfamiliarity",
            name="ck_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="userfamiliarity",
            name="ck_correct_le_total",
        ),
        migrations.RemoveIndex(
            model_name="userfamiliarity",
            name="UserFamilia_user_id_ee0932_idx",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="difficultyLevels",
            new_name="difficulty_id",
        ),
        migrations.RemoveField(
            model_name="userfamiliarity",
            name="cap_weighted_sum",
        ),
        migrations.RemoveField(
            model_name="userfamiliarity",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="userfamiliarity",
            name="weighted_correct",
        ),
        migrations.RemoveField(
            model_name="userfamiliarity",
            name="weighted_total",
        ),
        migrations.AddField(
            model_name="userfamiliarity",
            name="difficultyLevels",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Topic.difficultylevels",
            ),
        ),
        migrations.AlterField(
            model_name="userfamiliarity",
            name="correct_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userfamiliarity",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userfamiliarity",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
