# Generated by Django 5.2.4 on 2025-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0002_remove_userfamiliarity_uq_user_quiz_topic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="difficulty_id",
            new_name="difficulty",
        ),
    ]
