# Generated by Django 5.2.4 on 2025-08-13 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0003_rename_difficulty_id_topic_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfavorite",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Topic.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Topic.topic",
            ),
        ),
    ]
