# Generated by Django 5.2.4 on 2025-08-13 01:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0003_rename_difficulty_id_topic_difficulty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="userfamiliarity",
            name="difficultyLevels",
        ),
        migrations.AddField(
            model_name="userfamiliarity",
            name="cap_weighted_sum",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="userfamiliarity",
            name="difficulty_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Topic.difficultylevels",
            ),
        ),
        migrations.AddField(
            model_name="userfamiliarity",
            name="weighted_correct",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="userfamiliarity",
            name="weighted_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="userfamiliarity",
            name="correct_answers",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="userfamiliarity",
            name="total_questions",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="userfamiliarity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="userfamiliarity",
            index=models.Index(
                fields=["user", "quiz_topic"], name="UserFamilia_user_id_ee0932_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfamiliarity",
            constraint=models.UniqueConstraint(
                fields=("user", "quiz_topic"), name="uq_user_quiz_topic"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfamiliarity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("correct_answers__gte", 0), ("total_questions__gte", 0)
                ),
                name="ck_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfamiliarity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("correct_answers__lte", models.F("total_questions"))
                ),
                name="ck_correct_le_total",
            ),
        ),
    ]
