# Generated by Django 5.2.4 on 2025-08-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0004_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={},
        ),
    ]
