# Generated by Django 5.2.4 on 2025-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0004_userfavorite_quiz_alter_userfavorite_topic"),
        ("Topic", "0005_alter_topic_options"),
    ]

    operations = []
