# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0008_fix_difficulty_levels_table'),
    ]

    operations = [
        # 為 Topic 模型添加複合索引
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['difficulty', 'deleted_at'], name='topic_difficulty_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['quiz_topic', 'difficulty', 'deleted_at'], name='topic_quiz_difficulty_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['User_answer', 'deleted_at'], name='topic_user_answer_deleted_idx'),
        ),
        
        # 為 Quiz 模型添加複合索引
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', 'quiz_topic', 'deleted_at'], name='quiz_user_topic_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', 'created_at', 'deleted_at'], name='quiz_user_created_deleted_idx'),
        ),
        
        # 為 UserFamiliarity 模型添加索引
        migrations.AddIndex(
            model_name='userfamiliarity',
            index=models.Index(fields=['user', 'difficulty_level'], name='userfamiliarity_user_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='userfamiliarity',
            index=models.Index(fields=['quiz_topic', 'difficulty_level'], name='userfamiliarity_quiz_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='userfamiliarity',
            index=models.Index(fields=['familiarity', 'updated_at'], name='userfamiliarity_familiarity_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='userfamiliarity',
            index=models.Index(fields=['user', 'familiarity'], name='userfamiliarity_user_familiarity_idx'),
        ),
    ]
